#!/bin/sh
# Configure your favorite diff program here.
DIFF=diff

# Subversion provides the paths we need as the sixth and seventh 
# parameters.
LEFT=${6}
RIGHT=${7}

case $1 in
    -u) num=10 ;;
    *)  num=$1 ;;
esac

# Call the diff command (change the following line to make sense for
# your merge program).
$DIFF -U $num  $LEFT --label "$3" $RIGHT --label "$5" || exit 1

exit 0

# Return an errorcode of 0 if no differences were detected, 1 if some were.
# Any other errorcode will be treated as fatal.
