<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet version="1.0"
   xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
   xmlns:xs="http://www.w3.org/2001/XMLSchema" >

   <xsl:output  method="text" indent="no" encoding="ISO-8859-1" xml:space="default"/>

   <!-- apostroph -->
   <xsl:variable name="apos" select='"&apos;"'/>
   <!-- line end  -->
   <xsl:variable name="CR" select="'&#xa;'"/>
   <!-- continue on next line -->
   <xsl:variable name="CONT" select="concat(' \',$CR)"/>
   <!-- indentation -->
   <xsl:variable name="TAB" select="('    ')"/>
   
   <!--  -->
   <xsl:template match="/">
      <xsl:value-of select="concat('# $', 'Id', '$', $CR)"/>
      <xsl:value-of select="concat('# Do not edit! This file is automaticly generated by hwmon-inc.xsl',$CR,$CR)"/>
      <xsl:for-each select="rrd-graph">
         <xsl:call-template name="rrd-graph"/>
      </xsl:for-each>
      <xsl:value-of select="concat('# _oOo_',$CR)"/>
   </xsl:template>
   <!--  -->
   <xsl:template name="rrd-graph">
      <xsl:for-each select="graph">
         <xsl:call-template name="hwmon-func"/>
      </xsl:for-each>
      <xsl:call-template name="hwmon-main"/>
   </xsl:template>
   <!-- called with graph -->
   <xsl:template name="hwmon-func">
      <xsl:value-of select="concat('hwmon_',//header/@name,'_',@name,' ()',$CR)"/>
      <xsl:value-of select="concat('{',$CR)"/>
      <xsl:for-each select="group[1]">
         <xsl:for-each select="var">
            <xsl:call-template name="hwmon-var"/>
            <xsl:call-template name="hwmon-scale"/>
            <xsl:call-template name="hwmon-disp"/>
         </xsl:for-each>
      </xsl:for-each>
      <xsl:call-template name="hwmon-tab"/>
      <xsl:value-of select="concat('}',$CR,$CR)"/>
   </xsl:template>
   <!-- called with var -->
   <xsl:template name="hwmon-var">
      <xsl:value-of select="concat($TAB,'var',position(),'=`')"/>
      <xsl:choose>
         <xsl:when test="@sensor">
            <xsl:value-of select="'sensors -u '"/>
            <xsl:choose>
               <xsl:when test="hwmon/@chip">
                  <xsl:value-of select="hwmon/@chip"/>
               </xsl:when>
               <xsl:when test="../../hwmon/@chip">
                  <xsl:value-of select="../../hwmon/@chip"/>
               </xsl:when>
               <xsl:otherwise>
                  <xsl:value-of select="//hwmon/@chip"/>
               </xsl:otherwise>
            </xsl:choose>
            <xsl:value-of select="concat(' | grep ',@sensor,'_input | cut -d : -f 2')"/>
         </xsl:when>
         <xsl:when test="@cat">
            <xsl:value-of select="'cat '"/>
            <xsl:choose>
               <xsl:when test="cat/@path">
                  <xsl:value-of select="cat/@path"/>
               </xsl:when>
               <xsl:when test="../../cat/@path">
                  <xsl:value-of select="../../cat/@path"/>
               </xsl:when>
               <xsl:otherwise>
                  <xsl:value-of select="//cat/@path"/>
               </xsl:otherwise>
            </xsl:choose>
            <xsl:value-of select="concat('/',@cat)"/>
         </xsl:when>
      </xsl:choose>
      <xsl:value-of select="concat('`',$CR)"/>
   </xsl:template>
   <!-- called with var -->
   <xsl:template name="hwmon-scale">
      <xsl:variable name="pos" select="position()"/>
      <xsl:choose>
         <xsl:when test="@sensor">
            <xsl:if test="hw-scale">
               <xsl:variable name="count" select="count(hw-scale)"/>
               <xsl:for-each select="hw-scale">
                  <xsl:value-of select="concat($TAB,'var',$pos,'=$((${var',$pos,'} ',@op,' ',@val,'))',$CR)"/>
               </xsl:for-each>
            </xsl:if>
         </xsl:when>
         <xsl:when test="@cat">
            <xsl:if test="cat-scale">
               <xsl:variable name="count" select="count(cat-scale)"/>
               <xsl:for-each select="cat-scale">
                  <xsl:value-of select="concat($TAB,'var',$pos,'=$((var',$pos,' ',@op,' ',@val,'))',$CR)"/>
               </xsl:for-each>
            </xsl:if>
         </xsl:when>
      </xsl:choose>
   </xsl:template>
   <!-- called with var -->
   <xsl:template name="hwmon-disp">
      <xsl:variable name="pos" select="position()"/>
      <xsl:choose>
         <xsl:when test="starts-with(@sensor,'in')">
            <xsl:value-of select="concat($TAB,'var',$pos,'=`echo ${var',$pos,'}| sed ')"/>
            <xsl:value-of select="concat($apos,'s/[^0-9]*\([0-9]*\)\.\([0-9]\{3\}\).*/\1.\2/',$apos,'`',$CR)"/>
         </xsl:when>
         <xsl:when test="starts-with(@sensor,'temp')">
            <xsl:value-of select="concat($TAB,'var',$pos,'=`echo ${var',$pos,'}| sed ')"/>
            <xsl:value-of select="concat($apos,'s/[^0-9]*\([0-9]*\)\.\([0-9]\{1\}\).*/\1.\2/',$apos,'`',$CR)"/>
         </xsl:when>
         <xsl:when test="starts-with(@sensor,'fan')">
            <xsl:value-of select="concat($TAB,'var',$pos,'=`echo ${var',$pos,'}| sed ')"/>
            <xsl:value-of select="concat($apos,'s/[^0-9]*\([0-9]*\).*/\1/',$apos,'`',$CR)"/>
         </xsl:when>
      </xsl:choose>
   </xsl:template>
   <!-- called with graph -->
   <xsl:template name="hwmon-tab">
      <xsl:value-of select="concat($CR,$TAB,'show_tab_header ',@title,' no',$CR,$CR)"/>
      <xsl:value-of select="concat($TAB,'echo &quot;&lt;table class=',$apos,'normtable',$apos,'&gt;&quot;',$CR)"/>
      <xsl:value-of select="concat($TAB,'echo &quot;&lt;tr&gt;&quot;',$CR)"/>
      <xsl:value-of select="concat($TAB,'echo &quot;&lt;th&gt;','${_HWSUPP_HWMON_SENSOR}','&lt;/th&gt;&quot;',$CR)"/>
      <xsl:value-of select="concat($TAB,'echo &quot;&lt;th&gt;',@label,'&lt;/th&gt;&quot;',$CR)"/>
      <xsl:value-of select="concat($TAB,'echo &quot;&lt;/tr&gt;&quot;',$CR)"/>
      <xsl:for-each select="group[1]">
         <xsl:for-each select="var">
            <xsl:call-template name="hwmon-vartab"/>
         </xsl:for-each>
      </xsl:for-each>
      <xsl:value-of select="concat($TAB,'echo &quot;&lt;/table&gt;&quot;',$CR)"/>
      <xsl:value-of select="concat($CR,$TAB,'show_tab_footer',$CR)"/>
   </xsl:template>
   <!-- called with var -->
   <xsl:template name="hwmon-vartab">
      <xsl:value-of select="concat($TAB,'echo &quot;&lt;tr align=',$apos,'center',$apos,'&gt;&quot;',$CR)"/>
      <xsl:value-of select="concat($TAB,'echo &quot;&lt;td&gt;',@label,'&lt;/td&gt;&quot;',$CR)"/>
      <xsl:value-of select="concat($TAB,'echo &quot;&lt;td&gt;${var',position(),'}&lt;/td&gt;&quot;',$CR)"/>
      <xsl:value-of select="concat($TAB,'echo &quot;&lt;/tr&gt;&quot;',$CR)"/>
   </xsl:template>
   <!--  -->
   <xsl:template name="hwmon-main">
      <xsl:value-of select="concat('hwmon_',//header/@name,' ()',$CR,'{',$CR)"/>
      <xsl:for-each select="graph">
         <xsl:value-of select="concat($TAB,'hwmon_',//header/@name,'_',@name,$CR)"/>
      </xsl:for-each>
      <xsl:value-of select="concat('}',$CR,$CR)"/>
   </xsl:template>
</xsl:stylesheet>

