<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet version="1.0"
   xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
   xmlns:xs="http://www.w3.org/2001/XMLSchema" >

   <xsl:output  method="text" indent="no" encoding="ISO-8859-1" xml:space="default"/>

   <!-- apostroph -->
   <xsl:variable name="apos" select='"&apos;"'/>
   <!-- line end  -->
   <xsl:variable name="CR" select="'&#xa;'"/>
   <!-- continue on next line -->
   <xsl:variable name="CONT" select="concat(' \',$CR)"/>
   <!-- indentation -->
   <xsl:variable name="TAB" select="('    ')"/>
   
   <!--  -->
   <xsl:template match="/">
      <xsl:value-of select="concat('#!/bin/sh',$CR)"/>
      <xsl:value-of select="concat('# $', 'Id', '$', $CR)"/>
      <xsl:value-of select="concat('# Do not edit! This file is automaticly generated by rrd-cgi.xsl',$CR,$CR)"/>
      <xsl:for-each select="rrd-graph">
         <xsl:call-template name="rrd-graph"/>
      </xsl:for-each>
      <xsl:value-of select="concat($CR,'# _oOo_',$CR)"/>
   </xsl:template>
   <!--  -->
   <xsl:template name="rrd-graph">
      <xsl:value-of select="concat('. /srv/www/include/cgi-helper',$CR)"/>
      <xsl:value-of select="concat('# set_debug=yes',$CR,$CR)"/>
      <xsl:value-of select="concat('# Security',$CR)"/>
      <xsl:value-of select="concat('check_rights &quot;hwsupp&quot; &quot;view&quot;',$CR,$CR)"/>
      <xsl:value-of select="concat('# get some internal variables',$CR)"/>
      <xsl:value-of select="concat('. /var/run/hwsupp.conf',$CR,$CR)"/>
      
      <xsl:value-of select="concat('show_html_header &quot;',//header/@title,'&quot;',$CR,$CR)"/>
      
      <xsl:call-template name="rrd-include"/>
      <xsl:call-template name="extra-include"/>
      <xsl:call-template name="default-action"/>
      <xsl:call-template name="rrd-defines"/>
      <xsl:call-template name="action-list"/>
      <xsl:call-template name="tab-list"/>
      <xsl:call-template name="showtab"/>
      <xsl:value-of select="concat($CR,'show_html_footer',$CR)"/>
   </xsl:template>
   <!--  -->
   <xsl:template name="rrd-include">
      <xsl:if test="graph">
         <xsl:value-of select="concat('if [ -e /srv/www/include/rrd-common.inc ]',$CR)"/>
         <xsl:value-of select="concat('then',$CR)"/>
         <xsl:value-of select="concat($TAB,'. /srv/www/include/rrd-common.inc',$CR)"/>
         <xsl:value-of select="concat($TAB,'if [ -e /srv/www/include/rrd-',translate(//header/@name,'_','-'),'.inc ]',$CR)"/>
         <xsl:value-of select="concat($TAB,'then',$CR)"/>
         <xsl:value-of select="concat($TAB,' . /srv/www/include/rrd-',translate(//header/@name,'_','-'),'.inc',$CR)"/>
         <xsl:value-of select="concat($TAB,'fi',$CR)"/>
         <xsl:value-of select="concat('fi',$CR)"/>
      </xsl:if>      
   </xsl:template>
   <!--  -->
   <xsl:template name="extra-include">
      <xsl:for-each select="include">
         <xsl:value-of select="concat('if [ -e /srv/www/include/',@include,' ]',$CR)"/>
         <xsl:value-of select="concat('then',$CR)"/>
         <xsl:value-of select="concat($TAB,'. /srv/www/include/',@include,$CR)"/>
         <xsl:value-of select="concat('fi',$CR)"/>
      </xsl:for-each>
   </xsl:template>
   <!--  -->
   <xsl:template name="default-action">
      <xsl:value-of select="concat($CR,': ${FORM_action:=',//header/@name,'_')"/>
      <xsl:choose>
         <xsl:when test="graph">
            <xsl:value-of select="concat(graph[1]/@name,'}',$CR)"/>
         </xsl:when>
         <xsl:otherwise>
            <xsl:value-of select="concat(include[1]/@name,'}',$CR)"/>
         </xsl:otherwise>
      </xsl:choose>
   </xsl:template>
   <!--  -->
   <xsl:template name="rrd-defines">
      <xsl:if test="graph">
         <xsl:value-of select="concat('if [ -e /srv/www/include/rrd-common.inc ]',$CR)"/>
         <xsl:value-of select="concat('then',$CR)"/>
         <xsl:for-each select="graph">
            <xsl:value-of select="concat($TAB,': ${FORM_rrd_graphtime_',//header/@name,'_',@name,':=$rrd_default_graphtime}',$CR)"/>
         </xsl:for-each>
         <xsl:value-of select="concat($CR,$TAB,'eval local rrd_source_time=',$apos,'$FORM_rrd_graphtime_',$apos,'$rrd_source',$CR)"/>
         <xsl:value-of select="concat($TAB,': ${rrd_source_time:=$rrd_default_graphtime}',$CR)"/>
         <xsl:value-of select="concat('fi',$CR)"/>
      </xsl:if>
   </xsl:template>
   <!--  -->
   <xsl:template name="action-list">
      <xsl:value-of select="concat('action_list=&quot;&quot;',$CR)"/>
      <xsl:if test="graph">
         <xsl:value-of select="concat('if [ -e /srv/www/include/rrd-common.inc ]',$CR)"/>
         <xsl:value-of select="concat('then',$CR)"/>
         <xsl:value-of select="concat($TAB,'action_list=&quot;$action_list')"/>
         <xsl:for-each select="graph">
            <xsl:value-of select="concat(' ',@name)"/>
         </xsl:for-each>
         <xsl:value-of select="concat('&quot;',$CR)"/>
         <xsl:value-of select="concat('fi',$CR)"/>
      </xsl:if>
      <xsl:for-each select="include">
         <xsl:choose>
            <xsl:when test="@condition">
               <xsl:value-of select="concat('if [ &quot;', @condition,'&quot; = &quot;yes&quot; ]',$CR)"/>
               <xsl:value-of select="concat('then',$CR)"/>
               <xsl:value-of select="concat($TAB,'action_list=&quot;$action_list ',@name,'&quot;',$CR)"/>
               <xsl:value-of select="concat('fi',$CR)"/>
            </xsl:when>
            <xsl:otherwise>
               <xsl:value-of select="concat('action_list=&quot;$action_list ',@name,'&quot;',$CR)"/>
            </xsl:otherwise>
         </xsl:choose>
      </xsl:for-each>
   </xsl:template>
   <!--  -->
   <xsl:template name="tab-list">
      <xsl:value-of select="concat($CR,'tab_list=&quot;&quot;',$CR)"/>
      <xsl:value-of select="concat('for i in ${action_list}',$CR)"/>
      <xsl:value-of select="concat('do',$CR)"/>
      <xsl:value-of select="concat($TAB,'case $i in',$CR)"/>
      <xsl:for-each select="*">
         <xsl:choose>
            <xsl:when test="name()='graph'">
               <xsl:call-template name="label"/>
            </xsl:when>
            <xsl:when test="name()='include'">
               <xsl:call-template name="label"/>
            </xsl:when>
         </xsl:choose>
      </xsl:for-each>
      <xsl:value-of select="concat($TAB,'esac',$CR)"/>
      <xsl:value-of select="concat($TAB,'if [ &quot;$FORM_action&quot; = &quot;',//header/@name,'_$i&quot; ]',$CR)"/>
      <xsl:value-of select="concat($TAB,'then',$CR)"/>
      <xsl:value-of select="concat($TAB,$TAB,'tab_list=`echo &quot;$tab_list $label no&quot;`',$CR)"/>
      <xsl:value-of select="concat($TAB,'else',$CR)"/>
      <xsl:value-of select="concat($TAB,$TAB,'tab_list=`echo &quot;$tab_list $label $myname?action=')"/>
      <xsl:value-of select="concat(//header/@name,'_$i&quot;`',$CR)"/>
      <xsl:value-of select="concat($TAB,'fi',$CR)"/>
      <xsl:value-of select="concat('done',$CR)"/>
   </xsl:template>
   <!--  -->
   <xsl:template name="showtab">
      <xsl:value-of select="concat($CR,'show_tab_header $tab_list',$CR)"/>
      <xsl:value-of select="concat('case $FORM_action in',$CR)"/>
      <xsl:for-each select="include">
         <xsl:call-template name="extra-tab"/>
      </xsl:for-each>
      <xsl:value-of select="concat($TAB,'*)',$CR)"/>
      <xsl:value-of select="concat($TAB,$TAB,'rrd_open_tab_list $FORM_action',$CR)"/>
      <xsl:value-of select="concat($TAB,$TAB,'rrd_render_graph $FORM_action',$CR)"/>
      <xsl:value-of select="concat($TAB,$TAB,'rrd_close_tab_list',$CR)"/>
      <xsl:value-of select="concat($TAB,';;',$CR)"/>
      <xsl:value-of select="concat('esac',$CR)"/>
      <xsl:value-of select="concat($CR,'show_tab_footer',$CR)"/>
   </xsl:template>
   <!-- called with graph or extra -->
   <xsl:template name="label">
      <xsl:value-of select="concat($TAB,$TAB,@name,')',$CR)"/>
      <xsl:value-of select="concat($TAB,$TAB,$TAB,'label=$(translate_label &quot;',@tab,'&quot;)',$CR)"/>
      <xsl:value-of select="concat($TAB,$TAB,';;',$CR)"/>
   </xsl:template>
   <!-- called with extra -->
   <xsl:template name="extra-tab">
      <xsl:value-of select="concat($TAB,//header/@name,'_',@name,')',$CR)"/>
      <xsl:value-of select="concat($TAB,$TAB,@func,$CR)"/>
      <xsl:value-of select="concat($TAB,';;',$CR)"/>
   </xsl:template>
</xsl:stylesheet>

